apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-preprocessing
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster #cluster
  image: dksshddl/spark:3.5.3
  imagePullPolicy: Always #IfNotPresent, Always
  mainApplicationFile: s3a://spark-jobs/01_preprocessing.py
  sparkVersion: 3.5.3
  sparkConf:
#    spark.jars.packages: "org.apache.hadoop:hadoop-aws:3.3.4,software.amazon.awssdk:bundle:2.31.30,org.apache.hadoop:hadoop-common:3.3.4"
    spark.kubernetes.file.upload.path: "s3a://spark"
    spark.jars.ivy: "/tmp/.ivy2"
  hadoopConf:
    fs.s3a.endpoint: "http://minio.minio:80"
    fs.s3a.access.key: "admin"
    fs.s3a.secret.key: "admin123"
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    fs.s3a.path.style.access: "true"
    fs.s3a.connection.ssl.enabled: "false"
    fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark
  executor:
    instances: 1
    cores: 1
    memory: 512m
    serviceAccount: spark